### KELOMPOK 4 ###
### INSTALASI PACKAGE YANG DIPERLUKAN, JIKA SUDAH DI INSTTALL TIDAK PERLU DI RUN LAGI
# install.packages("arules")    # package untuk membuat association rules
# install.packages("arulesViz") # package untuk memvisualisasikan plot hasil rules yang dibuat
# install.package("dplyr")      # package untuk membenarkan nama pada dataset

#### LOAD PACKAGE ###
library(arules)
library(arulesViz)
library(dplyr)

### IMPORT DATA ###
data <- read.csv("C:/Users/Marvel/Downloads/transaksi_gabungan.csv", sep = ";")  # ganti sama direktori file yang sesuai
str(data)   # melihat struktur dataset
View(data)  # melihat dataset

### MELIHAT JUMLAH PRODUK UNIK
unique_items <- unique(unlist(strsplit(data$ITEM, ", ")))
num_unique_items <- length(unique_items)
num_unique_items  # menampilkan jumlah produk unik
# unique_items      # menampilkan produk unik yang ada

### PRA-PROSES DATA ###
### KARENA DATA TERLALU BERAGAM DISINI KAMI KELOMPOKAN LAGI AGAR MENJADI KATEGORI YANG SAMA
# HEALTHCARE & KEBERSIHAN
data$ITEM <- gsub("ACNES SEALING JELL|SERUM|MISCELLAR WATER|MOISTURIZER|MASKER WAJAH|MASKER WAJAH GARNIER|GARNIER PINK|GARNIER MEN|PELEMBAB WAJAH|SUNSCREEN|TONER|GARNIER|GARNIER MICELLAR WATER|MICELLAR WATER|KRIM ANALGESIK|KRIM WAJAH|HANDBODY|LOTION TUBUH|BODY LOTION|SKINCARE", "SKINCARE", data$ITEM)
data$ITEM <- gsub("CAT KUKU|FOUNDATION|LIPBALM|LIP CREAM|MASCARA|CUSHION|LIPTIN", "MAKEUP", data$ITEM)
data$ITEM <- gsub("GRANOLA|FITBAR|KRATINGDAENG|YOU-C 1000|REDOXON|MINUMAN VITAMIN|FOSFOR ANORGANIK|MINUMAN SERBUK VITAMIN C1000 SACHET|MINUMAN VITAMIN C1000|VITAMIN RAMBUT|VITAMIN|VITAMIN D|CALCIUM ION|YC1000|HEMATOLOGI LENGKAP|AMARYL M 30 TABLET", "VITAMIN", data$ITEM)
data$ITEM <- gsub("KASA STERIL|BEDAK BAYI|PLESTER|ANTISEPTIK|HAND SANITIZER|HAND SANITIZER|MINYAK TELON|BEDAK TABUR|ROKOK|TOLAK ANGIN|OBAT SAKIT KEPALA|OBAT PUSING", "OBAT", data$ITEM)
data$ITEM <- gsub("PEMBERSIH MULUT|LISTERINE", "PEMBERSIH MULUT", data$ITEM)
data$ITEM <- gsub("CLOSEUP|PEPSODENT|ORAL-B|ODOL|PASTA GIGI SENSODYNE|PASTA GIGI CLOSEUP|PASTA GIGI", "PASTA GIGI", data$ITEM)
data$ITEM <- gsub("ALAT SIKAT GIGI|DOT BAYI|SIKAT GIGI FORMULA|SIKAT GIGI PEPSODENT|SIKAT GIGI", "SIKAT GIGI", data$ITEM)
data$ITEM <- gsub("ALAT CUKUR|HANDUK|PERALATAN MANDI", "PERALATAN MANDI", data$ITEM)
data$ITEM <- gsub("HAIR TONIC|CONDITIONER|PEWARNA RAMBUT|SUNSILK|SHAMPO|PANTENE|SHAMPOO|SHAMPO|SAMPO|SAMPO CLEAR|SHAMPOO REJOYCE|SHAMPOO CLEAR|SHAMPOO HEAD & SHOULDER", "SHAMPOO", data$ITEM)
data$ITEM <- gsub("GIV|PENCUCI MUKA|SHINZUI FACIAL WASH|BIORE|WARDAH|NUVO|SABUN PEMBERSIH MUKA|SABUN MUKA|SABUN BAJU|SABN CUCI PIRING|SABUN CUCI PAKAIAN|SABUN CUCI MUKA|SABUN CUCI TANGAN|SABUN CUCI PIRING|SABUN NUVO|SABUN DETOL|SABUN LIFEBUOY|SABUN SCOTCHBRITE|SABUN GIV|SABUN CUCI MUKA WARDAH|SABUN CUCI MUKA GARNIER|SABUN PENCUCI MUKA|SABUN|SABUN MANDI|SABUN MANDI LIFEBOUY", "SABUN MANDI", data$ITEM)
  data$ITEM <- gsub("SABUN MANDI CUCI PAKAIAN", "SABUN MANDI", data$ITEM)
  data$ITEM <- gsub("SABUN MANDI CUCI", "SABUN MANDI", data$ITEM)
  data$ITEM <- gsub("SABUN MANDI PEL LANTAI", "SABUN MANDI", data$ITEM)
  data$ITEM <- gsub("SABUN MANDI PEL", "SABUN MANDI", data$ITEM)
  data$ITEM <- gsub("SABUN MANDI SKINCARE", "SABUN MANDI", data$ITEM)
data$ITEM <- gsub("HARPIC|ALAT PEMBERSIH KLOSET|HARPIC PEMBERSIH KLOSET", "PEMBERSIH KAMAR MANDI", data$ITEM)
data$ITEM <- gsub("HANSAPLAST|KAPAS|KAPAS WAJAH|KAPAS BAYGON|CUTTONBUD|COTONBUD|COTTON BUDS|COTTON BUD|PENYERAP LEMBAB|TISSU|TISSUE|MITU WIPE BLUE|TESSA TISSUE|TISSUE PASEO|TISU KERING|TISU|TISU BASAH", "TISU", data$ITEM)
data$ITEM <- gsub("SOFTEX|PEMBALUT", "PEMBALUT", data$ITEM)
data$ITEM <- gsub("POSH MEN|PARFUM|PERFUME|PARFUME|PARFUME|REFIL PARFUM|PARFUM AXE|PARFUM BAJU|DEODIRAN TELUR KECAP BUAH ROTI TISU|DEODARAN|DEODORAN|DEODORANT", "PEWANGI BADAN", data$ITEM)
data$ITEM <- gsub("SUNLIGHT|MAMA LEMON|PEMBERSIH PIRING|SPONGE|SPONS CUCI PIRING SCOTCH-BRITE|SPON|PENCUCI PIRING|SIKAT BOTOL", "PEMBERSIH ALAT MAKAN", data$ITEM)
  data <- data %>%
  mutate(ITEM = gsub("ALAT MASAK \\(PANCI, SPATULA, SENDOK\\)", "COOKWARE", ITEM))
data$ITEM <- gsub("DOWNY|PELEMBUT PAKAIAN|PELEMBUT PAKAIAN DOWNY|PELICIN PAKAIAN KISPRAY|KISPRAY|MOLTO|PELEMBUT PAKAIAN|SUSU KENTANG DETERJEN PERQLATAN MANDI AIR|PEWANGI SETRIKA|DETERJEM|PEWANGI PAKAIAN|PEWANGI BAJU|PENGHARUM PAKAIAN|RINSO|DAIA|DETERJEN|DETERGEN|DETERGEN ATTACK|DETERGEN RINSO|SABUN CUCI BAJU|SABUN CUCI|PEMBERSIH PAKAIAN", "PEMBERSIH PAKAIAN", data$ITEM)
data$ITEM <- gsub("PEMUTIH BAYCLIN|PEMUTIH", "PEMUTIH", data$ITEM)
data$ITEM <- gsub("POPOK BAYI|POPOK", "POPOK", data$ITEM)
data$ITEM <- gsub("SENDAL|KAOS KAKI|SEPATU|SWALLOW SJD|CELANA|BAJU|GANTUNGAN BAJU|SPREI|CELANA PENDEK|SOFTLENS|CAIRAN SOFTLENS|CELANA|KALUNG|LENSA KONTAK|KACAMATA|WIG|BAJU|MASKER|TOPI", "PAKAIAN", data$ITEM)
  data$ITEM <- gsub("SABUN MANDI PAKAIAN", "SABUN MANDI", data$ITEM)
data$ITEM <- gsub("SO KLIN|SO KLIN LANTAI|PEMBERSIH LANTAI PORSTEX|SABUN PEL LANTAI|SABUN PEL", "PEMBERSIH LANTAI", data$ITEM)
data$ITEM <- gsub("PENYEGAR RUANGAN|STELA|GLAD AOE PEONY|STELA|PENGHARUM RUANGAN|PENGHARUM RUANGAN STELLA|KAMPER|PEWANGI RAUANGAN|PEWANGI RUANGAN|KAPUR BARUS", "PEWANGI RUANGAN", data$ITEM)
data$ITEM <- gsub("FRESTEA|FRESSTEA|NU CHOCO HAZELNUTEA|FRESHTEA JASMINE|FRUIT TEA APPLE|S-TEE|FRUIT TEA|THAI TEA|MILK TEA|NII GREENTEA|MY TEA|ICHITAN THAI MILK TEA|JAVANA MELATI|ICHI OCHA|JAVANA|ICHITAN THAI TEA|THE PUCUK|ICHITAN|MINUMAN TEH|TEH TONG JI|TEH GELAS|TEH JAVANA|TEH TONG TJI|ES TEH|TEH BOTOL|TEH BOTOL SOSRO|TEH BOTOL KOTAK|TEH SOSRO|TEH POCI|TEH PUCUK|TEH PUCUK HARUM|TEH KOTAK|TEH KEMASAN|TEH CELUP|TEH", "TEH", data$ITEM)
data$ITEM <- gsub("MAICIH|HATARI|FF COCONUT TPK|RISOL MAYO|MAXI CORN|FUZO|TWISTKO|MAKANAN RINGAN|J&J PIATTOS|OISHI PILLOWS|QTELA|SINDE|JETZ|PRINGLES ORIGINAL|CITATO|JAPOTA|MAITOS|CHITATO|LAYS|PRINGLES|MIN-BEE|CHEETOS|SPONGE|DORITOS|MAMASUKA RUMPUT LAUT|KUSUKA KEJU BAKAR|GORENGAN|MARSHMALLOW|KUACI|KUACI REBO|KUACI FUZO|HAPPY TOS|KERIPIK PISANG|STIK KEJU|KERIPIK|KRIPIK|POTABEE|CHIKI|CHIKI(2)|OISHI POPPY|HELLO PANDA|BERNARD EASY BITE|MONDE|WAFLE|WAFER|POPCORN|TARO|NYAM-NYAM|TARO BALL|BRONDONG JAGUNG|ASTOR|SNACK|FISH SNACK WRAP|SNACK SAPI|SNACK BALADO 140|SNACK BAYI|SNACK BROWNIES|KUE|KUE OREO|KUE COKLAT", "SNACK", data$ITEM)
  data$ITEM <- gsub("SNACK SNACK", "SNACK", data$ITEM)
data$ITEM <- gsub("ES KOPI|NESCAFE GOLD|NESCAFE|OLATTE|INDOCAFE|TOP COFFE|LUWAK WHITE KOFFE|KAPAL API|KOPI SASET|KOPI ABC|KOPI GOODDAY|KOPI GAJAH|KOPI KAPAL API|KOPI", "KOPI", data$ITEM)
data$ITEM <- gsub("KOPI", "KOP", data$ITEM)
data$ITEM <- gsub("KOP", "KOPI", data$ITEM)
data$ITEM <- gsub("OBAT NYAMUK|HIT (PEMBUNUH NYAMUK)|LOTION ANTI NANYMUK|HIT|BAYGON|INSEKTISIDA|PEMBASMI NYAMUK|HIT (PEMBUNUH NYAMUK)|OBAT NYAMUK|VAPE|ONE PUSH VAPE|DORA RACUN TIKUS|GAJAH TIKUS TRAP|WHISKAS MAKANAN KUCING|REPELLANT NYAMUK", "REPELLANT HEWAN", data$ITEM)
  data$ITEM <- gsub("LOTION", "SKINCARE", data$ITEM)
  data <- data %>%
  mutate(ITEM = gsub("SKINCARE ANTI NYAMUK", "REPELLANT HEWAN", ITEM))
  data <- data %>%
  mutate(ITEM = gsub("REPELLANT HEWAN \\(PEMBUNUH NYAMUK\\)", "REPELLANT HEWAN", ITEM))
  

# KEBUTUHAN RUMAH TANGGA
data$ITEM <- gsub("MADU TJ|MADU|GULA PUTIH|GULA PASIR|GULA MERAH|GULA DIABET", "PEMANIS", data$ITEM)
data$ITEM <- gsub("DELMONTE|DELMONTE EXTRA HOT PET|MAYUMI|MAYONAISE|MAYONNAISE|SAMBAL|KECAP MANIS|KECAP ASIN|KECAP|SAUS MAKANAN RINGAN|SAUS SAMBAL|SAUS BULGOGI|SARDEN ABC SAUS TOMAT|SAUS GOCHUJANG|SAUS BOLOGNESE|SAUS SAMBAL EXTRA PEDAS ABC|SAUS TIRAM|SAUS TOMAT|SAUS TIRAM|SAOS ABC|SAOS SAMBEL|SAOS TERIYAKI|SAOS CABE|SAOS TIRAM|SAOS TOMAT|SAUS", "SAUS", data$ITEM)
  data$ITEM <- gsub("SAUS SNACK", "SAUS", data$ITEM)
data$ITEM <- gsub("SUNCO POUCH|MINYAK|PORVITA|VIDORAN|PROMINA|MINYAK WIJEN|MINYAK KELAPA|MINYAK GORENG FILMA|MINYAK GORENG SANIA|MINYAK GORENG", "MINYAK GORENG", data$ITEM)
data$ITEM <- gsub("TELOR|TELUR AYAM|TELUR AYAM NEGERI|TELUR GABUS|TELUR", "TELUR", data$ITEM)
data$ITEM <- gsub("BERAS RAMOS|BERAS", "BERAS", data$ITEM)
data$ITEM <- gsub("GARAM|PENYEDAP RASA|PERASA MAKANAN|LADAKU MERICA BUBUK|MERICA|LADA BUBUK|KALDU BUBUK|BONCABE|BON CABE|KALDU JAMUR|PENYEDAP|MASAKO|MASAKO SAPI|ROYCO|BUMBU INSTAN|BUMBU SASA|BUMBU DAPUR|BUMBU RACIK SAJIKU|MASAKO AYAM|BUMBU MAGIC|BUMBU TOMYUM|BUMBU RACIK|BUMBU RACIK SERBAGUNA|BUMBU|BUMBU NASI GORENG", "BUMBU DAPUR", data$ITEM)
  data <- data %>%
  mutate(ITEM = gsub("BUMBU DAPUR \\(SASA\\)", "BUMBU DAPUR", ITEM))
data$ITEM <- gsub("FRESTEA|FRESSTEA|NU CHOCO HAZELNUTEA|FRESHTEA JASMINE|FRUIT TEA APPLE|S-TEE|FRUIT TEA|THAI TEA|MILK TEA|NII GREENTEA|MY TEA|ICHITAN THAI MILK TEA|JAVANA MELATI|ICHI OCHA|JAVANA|ICHITAN THAI TEA|THE PUCUK|ICHITAN|MINUMAN TEH|TEH TONG JI|TEH GELAS|TEH JAVANA|TEH TONG TJI|ES TEH|TEH BOTOL|TEH BOTOL SOSRO|TEH BOTOL KOTAK|TEH SOSRO|TEH POCI|TEH PUCUK|TEH PUCUK HARUM|TEH KOTAK|TEH KEMASAN|TEH CELUP|TEH", "TEH", data$ITEM)
data$ITEM <- gsub("NESCAFE GOLD|NESCAFE|OLATTE|INDOCAFE|TOP COFFE|LUWAK WHITE KOFFE|KAPAL API|KOPI SASET|KOPI ABC|KOPI GOODDAY|KOPI GAJAH|KOPI KAPAL API|KOPI", "KOPI", data$ITEM)
data$ITEM <- gsub("CIMORY HONEY|CIMORY|DANCOW|SGM|REAL GOOD|GREENFIELDS|DIAMOND STR|CREAMER|ULTRA STRAWBERRY|ZEE|MILO|FRISIAN FLAG|UHT|HILO|OATSIDE|SUSU DANCOW|SUSU CIMORY|RICH CREME WHIP CREAM POWDER|BEAR BRAND|SUSU KENTAL MANIS|SUSU BENDERA|SUSU ULTRA|SUSU KENTAL MANIS CARNATION|SUSU UHT DIAMOND|SUSU UHT|SUSU BERUANG|SUSU BUBUK|SUSU 200ML|BEAR ORI 189ML|SUSU 250ML|SUSU KEDELAI|INDOMILK|SUSU INDOMILK|ULTRAMILK|ULTRA MILK|DAIRY MILK|SUSU|SUSU KENTANG DETERJEN PERQLATAN MANDI AIR", "SUSU", data$ITEM)
data$ITEM <- gsub("FLA|NATA DE COCO|BUBUK PUDING|PUDDING MANGGA|NUTRIJEL|AGAR - AGAR SWALLOW|BUBUK AGAR - AGAR|AGAR-AGAR STRAWBERRY|CENDOL|AGAR-AGAR", "AGAR-AGAR", data$ITEM)
data$ITEM <- gsub("PKT BREAD.CO|CHEESE CROISSANT|ROTI TAWAR|ROTI SARIROTI|MARTABAK|BOLEN LILIT|ROTI TAWAR JUMBO|DONAT|ROTI SARI ROTI|PRIME BREAD|SARI ROTI COKLAT KEJU|ROTI ISI", "ROTI", data$ITEM)
data$ITEM <- gsub("KRAFT CHEEDAR|KEJU|KEJU KRAFT|KEJU PRO CHIZ|KEJU CAKE|KEJU CRAFT|KEJU", "KEJU", data$ITEM)
data$ITEM <- gsub("BLUE BAND|MARGARIN BLUEBAND|MARGARIN|MENTEGA", "MENTEGA", data$ITEM)
  data$ITEM <- gsub("MINYAK GORENG MENTEGA", "MINYAK GORENG", data$ITEM)
data$ITEM <- gsub("SELAI STRAWBERRY|NUTELLA|OVOMALTINE|PASTA COKLAT", "SELAI", data$ITEM)
data$ITEM <- gsub("SEREAL|KOKO KRUNCH|NESTLE|NESTLE CEREAL|CEREAL KELLOGG'S|CEREAL", "SEREAL", data$ITEM)
data$ITEM <- gsub("KOREK GAS|GAS", "GAS", data$ITEM)
data$ITEM <- gsub("MANGKUK|CENTONG NASI", "ALAT DAPUR", data$ITEM)
data$ITEM <- gsub("SEGITIGA BIRU|RAGI|TEPUNG RAGI|MAIZENA|TEPUNG BERAS|TEPUNG TERIGU|TERIGU|TEPUNG KANJI|TEPUNG SERBAGUNA", "TEPUNG", data$ITEM)
data$ITEM <- gsub("BAKING SODA|BAKING POWDER", "BAKING SODA", data$ITEM)
data$ITEM <- gsub("KARA|SANTAN", "SANTAN", data$ITEM)
data$ITEM <- gsub("NUGET|FIESTA NUGGET|FIESTA CHICKEN NUGGET|NUGGET AYAM", "NUGGET", data$ITEM)
data$ITEM <- gsub("SOZZIZ|SOSIS|SOSIS INDOMARET|SOSIS KANZLER|CHAMP SOSIS|SOSIS HANZEL|SOSIS NUGGET|SOSIS KANZLER GOCHUJANG DAN KEJU|CHAMP SOSIS AYAM", "SOSIS", data$ITEM)
data$ITEM <- gsub("CEDEA CHIKUWA|CEDEA STICK KEPITING|DUMPLING CEDEA|CEDEA SALMON BALL|BASO|BASO URAT|BASO ORI|CEDEA BASO CUMI|BASO KEJU|CEDEA BASO UDANG|BAKSO KEJU|BAKSO ORI|BAKSO|KIRANA BASO SKL HIJAU", "BASO", data$ITEM)
data$ITEM <- gsub("BIHUN|SO'UN|SPAGETI|SPAGHETTI|SAMYANG|MI INSTAN|BIHUN JAGUNG|SARIMI|PASTA SPAGHETTI|SPAGHETI|MIEGHETTI|POP MIE|LEMONILO|INDOMIE|POPMIE|MIE GELAS|PASTA BAYI|BEST WOK MIE|MIE BURUNG DARA|MIE SAMYANG|MIE SEDAAP GORENG|RAMEN|MIE JUMBO|MIE GORENG|MIE INSTAN", "MIE", data$ITEM)
  data <- data %>%
  mutate(ITEM = gsub("MIE WADAH BASO \\(2\\)", "MIE", ITEM))
  data <- data %>%
  mutate(ITEM = gsub("MIE WADAH KR\\(2\\)", "MIE", ITEM))
data$ITEM <- gsub("JAGUNG|JAMUR|JAMUR ENOKI|SAWI PUTIH|JAMUR INOKITATE|BIHUN JAGUNG|SELADA|SELEDRI|SAYURAN SEGAR (WORTEL, BROKOLI, )|TIMUN|KANGKUNG|WORTEL|KOL|TAUGE|CABAI|PAKCOY|BAYAM|SAYUT", "SAYUR", data$ITEM)
  data$ITEM <- gsub("BROSAYURI", "SAYUR", data$ITEM)
  data <- data %>%
  mutate(ITEM = gsub("SAYURAN SEGAR \\(SAYUR, SAYUR, SAYUR\\)", "SAYUR", ITEM))
data$ITEM <- gsub("ISOPLUS COCO|HYDRA COCO|HYDRO COCO|COCO BIT SP GUAVA|ORANGE WATER|MOGU-MOGU|BUAVITA|BUAHVITA|PULPY ORANGE|LARUTAN CAP KAKI 3|SOFTDRINK|ES BUAH|JUS JERUK|JUS|NUTRIBOOST|MIZONE|LASEGAR|MINUMAN JUS|MINUMAN PROTEIN|MINUMAN ENERGI|MINUMAN BUAH|POCARI SWEAT|MINUMAN KESEHATAN|MINUMAN ISOTONIC|SARI KACANG IJO|GOOD MOOD|MINUMAN DINGIN|MINUMAN CINCAU|MINUMAN ISOTONIK|MINUMAN JERUK|MINUMANA THAILAND|MINUMAN JAHE|MINUMAN ION|AIR BER-ION|ES COKLAT", "MINUMAN", data$ITEM)
data$ITEM <- gsub("SPRIT|SPRITE|GREEN SANDS|TEBS|FANTA|COCA COLA|COCA-COLA|MINUMAN SPRITE|MOJITO|BINTANG|SODA LEMON|SODA|MINUMAN BERSODA|MINUMAN SODA|MINUMAN BERKARBONASI", "MINUMAN BERKARBONASI", data$ITEM)
data$ITEM <- gsub("BAKING MINUMAN BERKARBONASI", "BAKING SODA", data$ITEM)
data$ITEM <- gsub("ANGGUR|BUAH-BUAHAN (APEL, PISANG, JERUK)|APEL FUJI|ORANGE|LYCHEE|JERUK MEDAN|PEAR|NANAS|PEPAYA|PISANG|SALAK PONDOH|TOMAT|MELON|APEL|JERUK|SEMANGKA", "BUAH", data$ITEM)
  data <- data %>%
  mutate(ITEM = gsub("BUAH-BUAHAN \\(BUAH, BUAH, BUAH\\)", "BUAH", ITEM))
data$ITEM <- gsub("TAHU|TOFU", "TAHU", data$ITEM)
data$ITEM <- gsub("DAUN BAWANG|BAWANG PUTIH|BAWANG MERAH|BAWANG DAUN|BAWANG BOMBAY", "BAWANG", data$ITEM)

# MAKANAN & MINUMAN BERAT DAN RINGAN
data$ITEM <- gsub("RICOLA|MANISAN|YUPI|MANISAN (YUPI)|YUPI LITTLE STARS|KOPIKO|KOPIKO CANDY|ALPHELIEBE|CHUPA CHUPS|MENTOS|ALPHALIBE|MENTOS MINT|MENTOS CANDY|PERMEN|PREMEN|BLASTER|PERMEN KARET", "PERMEN", data$ITEM)
  data <- data %>%
  mutate(ITEM = gsub("PERMEN \\(PERMEN\\)", "PERMEN", ITEM))
data$ITEM <- gsub("GLICO POCKY|POCKY|CHOCOLATOS|CHOCO PIE|BENG BENG SHARE IT|TOBLERONE|SILVER QUEEN|KIT KAT|COKI-COKI|BENGBENG|SILVERQUEEN|CADBURY|DELFI CHICCHOC|BETTER|DELFI TAKE IT|CHIC CHOC|SNICKERS|CHACHA|KITKAT|KINDERJOY|CADBURY DAIRY MILK|DARK CHOCOLATTE|COKELAT|COKLAT SUSU|COKLAT DAN MINUMAN|COKLAT CADBURY|CERES|MESES|COKLAT", "COKLAT", data$ITEM)
  data$ITEM <- gsub("ROTI COKLAT", "ROTI", data$ITEM)
  data$ITEM <- gsub("COKLAT SUSU|COKLAT DAN SUSU|DARK CHOCKOPI", "COKLAT", data$ITEM)
data$ITEM <- gsub("MAICIH|HATARI|FF COCONUT TPK|RISOL MAYO|MAXI CORN,FUZO|TWISTKO|MAKANAN RINGAN|J&J PIATTOS|OISHI PILLOWS|QTELA|SINDE|JETZ|PRINGLES ORIGINAL|CITATO|JAPOTA|MAITOS|CHITATO|LAYS|PRINGLES|MIN-BEE|CHEETOS|SPONGE|DORITOS|MAMASUKA RUMPUT LAUT|KUSUKA KEJU BAKAR|GORENGAN|MARSHMALLOW|KUACI|KUACI REBO|KUACI FUZO|HAPPY TOS|KERIPIK PISANG|STIK KEJU|KERIPIK|KRIPIK|POTABEE|CHIKI|CHIKI(2)|OISHI POPPY|HELLO PANDA|BERNARD EASY BITE|MONDE|WAFLE|WAFER|POPCORN|TARO|NYAM-NYAM|TARO BALL|BRONDONG JAGUNG|ASTOR|SNACK|FISH SNACK WRAP|SNACK SAPI|SNACK BALADO 140|SNACK BAYI|SNACK BROWNIES|KUE|KUE OREO|KUE COKLAT", "SNACK", data$ITEM)
  data <- data %>%
  mutate(ITEM = gsub("SNACK\\(2\\)", "SNACK", ITEM))
data$ITEM <- gsub("NABATI|KHONG GUAN|BISKIES|GERY SALUT|NESTAR|ROYALE|LEXUS|MALKIST KEJU|GOODTIME|MALKIST|GO POTATO|COOKIE|BRIO POTATO BISCUTIT|SARIRAOS SIMPING|BISKUIT|OAT BISKUIT|BISKUIT REGAL|SARI GANDUM|ROMA KELAPA|BISKUIT ROMA|SLAI O LAI|SLAI OLAI|TANGO|GOOD TIME|ROMA MALKIST|SELAI OLAI|CRACKERS|SARI GANDUM|OREO|ROMA|BISKUIT", "BISKUIT", data$ITEM)
data$ITEM <- gsub("BRIO POTATO", "BISKUIT", data$ITEM)
data$ITEM <- gsub("BUBUR AYAM INSTAN|BATAGOR KUAH|BATAGOR|SEBLAK CAMPUR|SEBLAK|SOTO|DAN KARI|REGULER NASI|BUBUR RASA AYAM|BUBUR SOTO|BUBUR AYAM|NASI PADANG|CHICKEN STEAK|NASI GORENG|KATSU EGG|NASI AYAM BETUTU", "MAKANAN BERAT", data$ITEM)
data$ITEM <- gsub("DAGING AYAM|AYAM GEPREK|AYAM KRISPY|AYAM GORENG|AYAM", "AYAM", data$ITEM)
data$ITEM <- gsub("DAGING SAPI|DAGING", "SAPI", data$ITEM)
data$ITEM <- gsub("IKAN SALMON|IKAN|UDANG", "SEAFOOD", data$ITEM)
data$ITEM <- gsub("KERUPUK|KRUPUK", "KERUPUK", data$ITEM)
data$ITEM <- gsub("ONIGIRI|ONIGIRI(2)|NASI SEGITA 100G|NASI SEGITIGA MAYO (2)|SUPER BUBUR|KORNET 200G|SARDEN|KORNET|SUP INSTAN|BUBUR AYAM INSTAN", "MAKANAN INSTAN", data$ITEM)
  data <- data %>%
  mutate(ITEM = gsub("MAKANAN INSTAN\\(2\\)", "MAKANAN INSTAN", ITEM))
  data <- data %>%
  mutate(ITEM = gsub("NASI SEGITIGA MAYO \\(2\\)", "MAKANAN INSTAN", ITEM))
data$ITEM <- gsub("FRENCH FRIES|ABON|ZUPPA SOUP|PIZZA|KENTANG GORENG|KENTANG|BURGER", "MAKANAN CEPAT SAJI", data$ITEM) 
data$ITEM <- gsub("SUSU MAKANAN CEPAT SAJI PEMBERSIH PAKAIAN PERQLATAN MANDI AIR", "MAKANAN CEPAT SAJI", data$ITEM)
data$ITEM <- gsub("MUJIGAE|ODENG|GOCHUJANG|TTEOK|TOPPOKI INSTAN|TTEOKBOKI|JAJJANGMYEON|MAKANAN KOREA", "MAKANAN KOREA", data$ITEM)
data$ITEM <- gsub("SUKRO|PILUS GARUDA|MAYASI|NUTS|GARUDA PILUS|TIC TAC|SUKRO|GARUDA KACANG|KACANG ATOM|KACANG GARUDA|KACANG DUA KELINCI|KACANG TANAH", "KACANG", data$ITEM)
data$ITEM <- gsub("NORI|BON NORI|RUMPUT LAUT", "RUMPUT LAUT", data$ITEM)
data$ITEM <- gsub("INFUSED WATER|LE MINERALE|AQUA|AQUA GELAS DUS|MINERAL WATER KEMASAN BOTOL|AQUA BOTOL|AQUA GALON|AQUA GELAS BOX|AIR GELAS DUS|AIR CUP AQUA|AIR GALON AQUA|PRISTINE AIR MINERAL|PRISTINE|PRISTINE BOTOL|AIR KEMASAN BOTOL PRISTINE|AIR MINERAL CLEO|1L|AIR KEHIDUPAN 1|AIR MINERAL 1500|AIR MINERAL 750|AIR MINERAL|AIR", "AIR", data$ITEM)
data$ITEM <- gsub("WALLS|AICE|CHAMPINA|CORNETO MINI|BOBA SUNDAE|STTRAWBERRY LUCKY SUNDAE|CHOCOLATE LUCKY SUNDAE|ICE CREAM|RAINBOW POWER WALLS|CORNETTO|WALLS ICE CREAM|ES KRIM WALLS|ESKRIM|ES KRIM", "ES KRIM", data$ITEM)
data$ITEM <- gsub("GREEK|YOHURT|YOGURT|YAKULT CITRUN|YAKULT|YOGURT BLUBERRY|YOGURT STROBERRY|YOGURT BLUEBERRY|YOGHURT|YOGHURT CIMORY|KBPS YOGHURT PLAIN", "YOGHURT", data$ITEM)
  data$ITEM <- gsub("YOGHURT YOGHURT|YOGHURT SUSU|SUSU YOGHURT", "YOGHURT", data$ITEM)
data$ITEM <- gsub("EXTRA JOSS|NUTRI SARI|NUTRISARI|TEMULAWAK|ENERGEN|QUAKER|BAJIGUR|WDANK|MATCHA INSTAN|ADEM SARI|MALANG SARI ASEM|SARI|ADEMSARI", "MINUMAN BUBUK", data$ITEM)
  data$ITEM <- gsub("MINUMAN BUBUK ROTI", "MINUMAN BUBUK", data$ITEM)
data$ITEM <- gsub("MARJAN|MARJAN COCOPANDAN|SIRUP", "SIRUP", data$ITEM)

# LAINNYA
data$ITEM <- gsub("RAM|KIPAS|HANDPHONE|SALDO|KABEL CHARGER|EARPHONE|KABEL|PULSA|KUOTA|KABEL CHARGER TYPE C|PRINTER INK|LAMPU|LAMPU BOHLAM|KABEL VGA|USB|HEADSET|LAPTOP|KABEL HDMI|SPEAKER|HARD DRIVE|TINTA|MOUSE|MOUSE PAD|CCTV|KEYBOARD|WEBCAM|ADAPTOR|MONITOR|BATERAI|BATERAI LAPTOP|BATERAI ABC", "ELEKTRONIK", data$ITEM)
  data$ITEM <- gsub("ELEKTRONIK ELEKTRONIK", "ELEKTRONIK", data$ITEM)
data$ITEM <- gsub("KERTAS|FOX|KENKO CUTTER|MATERAI|BUKU|PENGHAPUS|PENSIL|PULPEN|PULPEN FABER CASTELL|PENSIL FABER CASTELL", "ALAT TULIS", data$ITEM)
  data$ITEM <- gsub("ALAT TULIS NASI", "ALAT TULIS", data$ITEM)
data$ITEM <- gsub("KLINPAK CLING WRAP JUMBO REFFIL|TRASH BAG|PLASTIK|PLASTIK WRAP|PLASTIK BESAR", "PLASTIK", data$ITEM)
data$ITEM <- gsub("DAZEL SLS|DAZEL SELIMUT|CILUNG|CEMCEM|WAGON CONTAINER BOX|BOLA|RAKET TENIS|RAJAWALI TS PANJANG LABEL KUNING XL|KARPET|CERMIN|KERTAS NASI|CALUNG|INDOMARET|TIKET|FILM|ANGKOT|KOIN|KURSI|ATM|KARTU|MAINAN|TUSUK GIGI", "LAINNYA", data$ITEM)

### MELIHAT KEMBALI JUMLAH PRODUK UNIK
unique_items <- unique(unlist(strsplit(data$ITEM, ", ")))
num_unique_items <- length(unique_items)
num_unique_items
unique_items

View(data)  # menampilkan tabel dataset
head(data)  # menampilkan sebagian data

### MEMBUAT ASSOCIATION RULES ###
data <- as.data.frame(data)
transactions <- strsplit(data$ITEM, ", ")
trans <- as(transactions, "transactions")
rules <- apriori(
    trans, 
    parameter = list(
        minlen = 1,  
        support = 0.0035, 
        confidence = 0.0035, 
        target = "rules"
    )
)

inspect(sort(rules, by = 'lift')) # menampilkan rules yang telah dibuat
plot(sort(rules, by = 'lift'))    # visualisasi rules dengan plot
# plot(arules::inspect(rules))

### MEMBUAT FUNGSI PREDIKSI ###
# MEMBUAT PREDIKSI BERDASARKAN RULES YANG TELAH DIBUAT SEBELUMNYA
make_predictions <- function(new_transaction, rules) {
  matching_rules <- subset(rules, subset = lhs %in% new_transaction)  
  recommended_items <- unique(unlist(rhs(matching_rules)))            
  return(recommended_items)                                           
}

### MELAKUKAN PREDIKSI DARI DATA TRANSAKSI BARU
new_transaction <- c("SHAMPOO", "SABUN MANDI", "PERMEN")      # ganti dengan data transaksi baru yang ingin di prediksi
predicted_items <- make_predictions(new_transaction, rules)   # memanggil fungsi untuk memberi prediksi/rekomendasi dari transaksi baru
inspect(predicted_items)                                      # menampilkan barang yang di rekomendasikan
